# Generated by Django 3.1.1 on 2020-09-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('restaurant', models.CharField(max_length=100)),
                ('delivery_fee', models.CharField(max_length=100)),
                ('delivery_time', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('restaurants', models.ManyToManyField(to='main_app.Restaurant')),
            ],
        ),
    ]
