# Generated by Django 3.1.1 on 2020-09-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200928_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Users',
        ),
    ]
