# Generated by Django 3.1.1 on 2020-10-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_restaurant_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='delivery_fee',
            new_name='delivery_data',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='delivery_time',
        ),
    ]
